### ISSUE TITLE
trouble using predefined :prev_app tos definition

### ISSUE THREAD

**Issue by njm2112** [yqrashawn/yqdotfiles#3]
In [./config/karabiner.edn](github.com/yqrashawn/yqdotfiles/blob/master/.config/karabiner.edn), you define `:prev_app` ([line 4](https://github.com/yqrashawn/yqdotfiles/blob/master/.config/karabiner.edn#L4)) as a `:tos` definition, but I'm having trouble using it with your later-defined `right_command` re-mapping ([lines 287-289](https://github.com/yqrashawn/yqdotfiles/blob/master/.config/karabiner.edn#L287)):

```
➜  ~ goku
ERROR: invalid <to> in main section's Change right_command ...
Failed!
```

It seems that there's nothing defined for `:application` anywhere else in your config, but the \<to\> part of the rule invokes that at [line 289](https://github.com/yqrashawn/yqdotfiles/blob/master/.config/karabiner.edn#L289): `[:application :right_command nil {:alone :prev_app}]`.

**Could you clarify what is intended by `:application` and why it might not be working for me?**

**Comment by yqrashawn** [comment]
There's an `application` key on one of my keyboards. Maybe a filco minila?

Yes, found the keymap image. Beside the left arrow.

![image](https://user-images.githubusercontent.com/15090582/79626155-8a93b180-8160-11ea-9d03-ce787c5d90d3.png)
